/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elWahabi.formpersonas;
import elWahabi.formpersonas.datos.PoolPersonas;
import elWahabi.formpersonas.model.Persona;
import elWahabi.formpersonas.model.Sexo;
import java.util.ArrayList;

/**
 *
 * @author Lamiae
 */
public class BuscarPersonas extends javax.swing.JFrame {

    private final PoolPersonas poolPersonas;
    /**
     * Creates new form BuscarPersonas
     */
    public BuscarPersonas() {
        initComponents();
        poolPersonas = new PoolPersonas();
    }
    //Metodo para mostrar resultados 
    private void mostrarResultados(ArrayList<Persona> personas) {
        jTextArea1.setText("");
        personas.forEach((p) -> {
            jTextArea1.setText(jTextArea1.getText()+p+"\n");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMas = new javax.swing.JButton();
        jButtonFem = new javax.swing.JButton();
        jButtonJub = new javax.swing.JButton();
        jButtonMenEdad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelBuscar = new javax.swing.JLabel();
        jLabelResu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMas.setText("Buscar personas: masculinas");
        jButtonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 180, -1));

        jButtonFem.setText("Buscar personas: femininas");
        jButtonFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFemActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, -1));

        jButtonJub.setText("Buscar personas: jubilados");
        jButtonJub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJubActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJub, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 210, -1));

        jButtonMenEdad.setText("Buscar personas: menores de edad");
        jButtonMenEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenEdadActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMenEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 210, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 136, 380, 180));

        jLabelBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelBuscar.setForeground(new java.awt.Color(51, 0, 255));
        jLabelBuscar.setText("Buscar personas");
        getContentPane().add(jLabelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 100, -1));

        jLabelResu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelResu.setForeground(new java.awt.Color(0, 0, 255));
        jLabelResu.setText("Resultado de la busqueda");
        getContentPane().add(jLabelResu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasActionPerformed
        // TODO add your handling code here:
          mostrarResultados(poolPersonas.buscarPorSexo(Sexo.masculino));
    }//GEN-LAST:event_jButtonMasActionPerformed

    private void jButtonJubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJubActionPerformed
        // TODO add your handling code here:
          mostrarResultados(poolPersonas.buscarPorEdad(67, 120));
        
    }//GEN-LAST:event_jButtonJubActionPerformed

    private void jButtonFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFemActionPerformed
        // TODO add your handling code here:
         mostrarResultados(poolPersonas.buscarPorSexo(Sexo.femenino));
        
    }//GEN-LAST:event_jButtonFemActionPerformed

    private void jButtonMenEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenEdadActionPerformed
        // TODO add your handling code here:
         mostrarResultados(poolPersonas.buscarPorEdad(0, 17));
        
    }//GEN-LAST:event_jButtonMenEdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarPersonas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFem;
    private javax.swing.JButton jButtonJub;
    private javax.swing.JButton jButtonMas;
    private javax.swing.JButton jButtonMenEdad;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelResu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
