/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elWahabi.formpersonas;

import elWahabi.formpersonas.datos.PoolPersonas;
import elWahabi.formpersonas.model.Persona;
import elWahabi.formpersonas.model.Sexo;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Lamiae
 */
public class FormularioPersonas extends javax.swing.JFrame {
    
    private final PoolPersonas poolPersonas;
    /**
     * Creates new form FormularioPersonas
     */
    public FormularioPersonas() {
        initComponents();
        //Instanciar el objeto poolpersonas de la clase poolPersonas
        poolPersonas = new PoolPersonas();
    }
    //Metodo para actualizar la lista de personas
     public void actualizarLista() {
        ArrayList<Persona> todos = poolPersonas.getTodos();
        jTextArea1 .setText("");
        todos.forEach((p) -> {
            jTextArea1 .setText(jTextArea1 .getText()+p+"\n");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNom = new javax.swing.JTextField();
        jLabelNom = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelSexo = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jButtonCrear = new javax.swing.JButton();
        jScrollPaneList = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelList = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 90, -1));

        jLabelNom.setText("Nombre");
        getContentPane().add(jLabelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 27, 53, -1));

        jLabelEdad.setText("Edad");
        getContentPane().add(jLabelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 50, -1));
        getContentPane().add(jTextFieldEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 90, -1));

        jLabelSexo.setText("Sexo");
        getContentPane().add(jLabelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        jComboBoxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 90, -1));

        jButtonCrear.setText("Crear Persona");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPaneList.setViewportView(jTextArea1);

        getContentPane().add(jScrollPaneList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 156, 360, 170));

        jLabelList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelList.setForeground(new java.awt.Color(0, 0, 255));
        jLabelList.setText("Lista personas");
        getContentPane().add(jLabelList, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 120, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexoActionPerformed

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        // TODO add your handling code here:
        String nombre = jTextFieldNom.getText();
        String edad =  jTextFieldEdad.getText();
        Sexo sexo;
        if (jComboBoxSexo.getSelectedIndex()==0) {
            sexo = Sexo.masculino;
        }else{
            sexo=Sexo.femenino;
        }
        
        if (!nombre.equals("")
            &&!edad.equals("")) {
            try {
                int edadnum = Integer.parseInt(edad);
                Persona persona = new Persona(nombre,edadnum,sexo);
                if (!poolPersonas.addPersona(persona)){
                    JOptionPane.showMessageDialog(this, "Ya hay 10 personas en la lista.");
                }
                actualizarLista();
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Edad no válida. Introduzca solamente números.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No pueden estar vacíos los campos nombre y edad.");
        }
    }
     private void salidaPersonasMouseClicked(java.awt.event.MouseEvent evt) {
            actualizarLista();
    }//GEN-LAST:event_jButtonCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPersonas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelList;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JScrollPane jScrollPaneList;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldNom;
    // End of variables declaration//GEN-END:variables
}
